### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by mstc-xqp** [ivineetm007/Fall-detection#1]
Thank you very much for your wonderful work!
Could u please guide  how to run the code ?

I am so confused!

Thank you very much

**Comment by ivineetm007** [comment]
Check the Readme inside the [mrfd](https://github.com/ivineetm007/Fall-detection/blob/master/mrfd) folder. It would be better to have a look at the paper to understand each component. 
Let me know which component is ambiguous.

**Comment by mstc-xqp** [comment]
> Check the Readme inside the [mrfd](https://github.com/ivineetm007/Fall-detection/blob/master/mrfd) folder. It would be better to have a look at the paper to understand each component.
> Let me know which component is ambiguous.

can i use the depth picture to test?

or  i use depth picuture to train.

like UR Dataset

**Comment by ivineetm007** [comment]
The proposed method consists of person tracking, data preprocessing, and model training. 
Person tracking
For depth data, you need to make changes to the person tracking method. The current tracker consists of rfcn object detector, Kalman filtering, and contour box localization for thermal data. You can make changes in these methods for depth data or can use another method but you need to store the tracked bounding boxes in the same format and at the same location to use the later code. Check the format of the bounding boxes used in this code- [https://drive.google.com/drive/folders/1BJLvY-z0UZxV2G1CuAWQjiPh0NvzrqlJ](https://drive.google.com/drive/folders/1BJLvY-z0UZxV2G1CuAWQjiPh0NvzrqlJ) 
Data processing and model training
Data processing is done automatically when you run the train files but you need to configure the data paths and data variables for the new dataset. You can start with the train files and check the functions called while training.

**Comment by mstc-xqp** [comment]
> The proposed method consists of person tracking, data preprocessing, and model training for thermal data. You can make changes to train for depth data. Check the [demo](https://github.com/ivineetm007/Fall-detection/blob/master/mrfd/demo.ipynb) file to understand each step involved while processing data. While training, these steps are done in steps by storing and loading while training as described below:-
> Person tracking
> For depth data, you need to make changes to the person tracking method. The current tracker consists of rfcn object detector, Kalman filtering, and contour box localization for thermal data. You can make changes in these methods for depth data or can use another method but you need to store the tracked bounding boxes in the same format and at the same location to use the later code. Check the format of the bounding boxes used in this code- https://drive.google.com/drive/folders/1BJLvY-z0UZxV2G1CuAWQjiPh0NvzrqlJ
> Data processing and model training
> Data processing is done automatically when you run the train files but you need to configure the data paths and data variables for the new dataset. You can start with the train files and check the functions called while training.

hi  i have seen your other  "Spatio-Temporal Adversarial Learning for Detecting Unseen Falls"

this work is without  person tracking but use the  Adversarial Learning. 

what if  skip the  Adversarial Learning and train the depth image.
